const teamImageMap = {
    "Akron": "/Team_Logos/Akron_Zips.png",
    "Alabama Crimson Tide": "/Team_Logos/Alabama_Crimson_Tide.png",
    "Alabama-Birmingham": "/Team_Logos/Alabama-Birmingham.png",
    "Arizona": "/Team_Logos/Arizona_Wildcats.png",
    "Auburn": "/Team_Logos/Auburn_Tigers.png",
    "Baylor": "/Team_Logos/Baylor_Bears.png",
    "Boise State": "/Team_Logos/Boise_State_Broncos.png",
    "BYU": "/Team_Logos/Brigham_Young_Cougars.png",
    "Clemson": "/Team_Logos/Clemson_Tigers.png",
    "Colgate": "/Team_Logos/Colgate_Raiders.png",
    "College of Charleston": "/Team_Logos/College_of_Charleston.png",
    "Colorado": "/Team_Logos/Colorado_Buffaloes.png",
    "Colorado State": "/Team_Logos/Colorado_State_Rams.png",
    "Connecticut": "/Team_Logos/Connecticut_Huskies.png",
    "Creighton": "/Team_Logos/Creighton_Bluejays.png",
    "Dayton": "/Team_Logos/Dayton_Flyers.png",
    "Drake": "/Team_Logos/Drake_Bulldogs.png",
    "Duke": "/Team_Logos/Duke_Blue_Devils.png",
    "Duquesne": "/Team_Logos/Duquesne_Dukes.png",
    "FAU": "/Team_Logos/Florida_Atlantic_Owls.png",
    "Florida": "/Team_Logos/Florida_Gators.png",
    "Gonzaga": "/Team_Logos/Gonzaga_Bulldogs.png",
    "Grambling State": "/Team_Logos/Grambling_State_Tigers.png",
    "Grand Canyon": "/Team_Logos/Grand_Canyon_Antelopes.png",
    "Houston": "/Team_Logos/Houston_Cougars.png",
    "Howard": "/Team_Logos/Howard_Bison.png",
    "Illinois": "/Team_Logos/Illinois_Fighting_Illini.png",
    "Iowa State": "/Team_Logos/Iowa_State_Cyclones.png",
};

  export default teamImageMap;